# Spring Boot Configuration
# application.yml
# src/main/resources/**
spring:
  application:
    name: myNutrition
  profiles:
    active: local # local, dev, prod (커밋 전에 항상 dev로 변경)
    include:   # JWT, AWS, EMAIL, LOGIN, OAUTH2
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    groups-order: DESC
    doc-expansion: list
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true