# .github/workflows/deploy.yml

name: CI/CD Deploy on 'main' push

on:
  push:
    branches: [ chore/docker ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot Application
        run: ./gradlew build -x test

      - name: 디렉토리 구조 확인
        run: ls -R

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t gisu1102/my-nutrition:latest 
          docker push gisu1102/my-nutrition:latest

      - name: Sync backend-resources (rsync) to EC2
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./backend-resources/
          remote_path: /home/ubuntu/backend-resources/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/backend-resources
            docker pull gisu1102/my-nutrition:latest
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d